language: node_js
node_js:
- '0.10'
- '0.12'
- '1.8'
- '2.5'
- '3.3'
- '4.4'
- '5.11'
- '6.2'
before_install:
- bash _scripts/install.sh

before_script:
- echo -e "Host 188.166.58.138\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_success:
- bash _scripts/deploy.sh
